#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>

/*

Output generated by this code - 

Parent process forks in this order: context switching after forking child 0,1,2

00 10 01 11 20 02 

Parent is doing iterating from i = 0 to 5 (we can't see it because os scheduler doesn't get to it)
Think of a manager who is done assigning tasks before the workers are done their work (as usual)

Prints this line: Parent about to terminate
return 0 is called - this is to end the main program which is the same as calling exit on the parent

HOWEVER, parent process isn't terminated right away. 
The child processes are still running at this time which is why we see:

12 31 30 03 13 22 31 04 being printed 

NOW the parent dies so the children who are scheduled to print by the os, 
when they print their ppid is 1 because all these children now dont have a parent and will be adopted by 
the init process whos pid is 1. 


[81786] Original process (my parent is 81176)
[81790] Child 0 0 (parent pid = 81786)
[81791] Child 1 0 (parent pid = 81786)
[81790] Child 0 1 (parent pid = 81786)
[81791] Child 1 1 (parent pid = 81786)
[81792] Child 2 0 (parent pid = 81786)
[81790] Child 0 2 (parent pid = 81786)
[81786] Parent about to terminate
[81791] Child 1 2 (parent pid = 81786)
[81792] Child 2 1 (parent pid = 81786)
[81793] Child 3 0 (parent pid = 81786)
[81790] Child 0 3 (parent pid = 81786)
[81791] Child 1 3 (parent pid = 81786)
[81792] Child 2 2 (parent pid = 81786)
[81793] Child 3 1 (parent pid = 81786)
[81790] Child 0 4 (parent pid = 81786)
[81794] Child 4 0 (parent pid = 1)
[81791] Child 1 4 (parent pid = 1)
[81792] Child 2 3 (parent pid = 1)
[81793] Child 3 2 (parent pid = 1)
[81794] Child 4 1 (parent pid = 1)
[81792] Child 2 4 (parent pid = 1)               
[81793] Child 3 3 (parent pid = 1)
[81794] Child 4 2 (parent pid = 1)
[81793] Child 3 4 (parent pid = 1)
[81794] Child 4 3 (parent pid = 1)
[81794] Child 4 4 (parent pid = 1)


*/

int main() {
    int result;
    int i, j;

    printf("[%d] Original process (my parent is %d)\n",
            getpid(), getppid());

    for(i = 0; i < 5; i++) {
        result = fork();

        if(result == -1) {
            perror("fork:");
            exit(1);
        } else if (result == 0) { //child process
            for(j = 0; j < 5; j++) {
                printf("[%d] Child %d %d (parent pid = %d)\n",
                        getpid(), i, j, getppid());
                usleep(100);
            }
            exit(0);
        }
    }
    printf("[%d] Parent about to terminate\n", getpid());
    
    return 0;

}